{
 "title": "Node Exporter Server Metrics",
 "tags": [ "templated" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DISPONIBILITE LOAD BALANCING",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.56.10:9100\"}"
    },
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DISPONIBILITE SERVER WEB MASTER",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.56.20:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISPONIBILITÉ SERVER  WEB  SLAVE",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.56.30:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISPONIBILITÉ SERVER BD MASTER",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.56.40:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISPONIBILITÉ SERVER BD SLAVE",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.56.40:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}